//name : main_0
//input : input_data_out:16
//output : output_address:16
//output : output_we:16
//output : output_data_in:16
//source_file : single_port_ram_tb.c

///+============================================================================+
///|                                                                            |
///|                     This file was generated by Chips                       |
///|                                                                            |
///|                                  Chips                                     |
///|                                                                            |
///|                      http://github.com/dawsonjon/Chips-2.0                 |
///|                                                                            |
///|                                                             Python powered |
///+============================================================================+
module main_0(input_data_out,input_data_out_stb,output_address_ack,output_we_ack,output_data_in_ack,clk,rst,output_address,output_we,output_data_in,output_address_stb,output_we_stb,output_data_in_stb,input_data_out_ack,exception);
  integer file_count;
  parameter  stop = 3'd0,
  instruction_fetch = 3'd1,
  operand_fetch = 3'd2,
  execute = 3'd3,
  load = 3'd4,
  wait_state = 3'd5,
  read = 3'd6,
  write = 3'd7;
  input [31:0] input_data_out;
  input input_data_out_stb;
  input output_address_ack;
  input output_we_ack;
  input output_data_in_ack;
  input clk;
  input rst;
  output [31:0] output_address;
  output [31:0] output_we;
  output [31:0] output_data_in;
  output output_address_stb;
  output output_we_stb;
  output output_data_in_stb;
  output input_data_out_ack;
  reg [31:0] timer;
  reg [63:0] timer_clock;
  reg [15:0] program_counter;
  reg [15:0] program_counter_1;
  reg [15:0] program_counter_2;
  reg [44:0] instruction;
  reg [4:0] opcode_2;
  reg [3:0] a;
  reg [3:0] b;
  reg [3:0] z;
  reg write_enable;
  reg [3:0] address_a_2;
  reg [3:0] address_b_2;
  reg [3:0] address_z_2;
  reg [3:0] address_z_3;
  reg [31:0] load_data;
  reg [31:0] write_output;
  reg [31:0] write_value;
  reg [31:0] read_input;
  reg [15:0] literal_2;
  reg [31:0] a_hi;
  reg [31:0] b_hi;
  reg [31:0] a_lo;
  reg [31:0] b_lo;
  reg [63:0] long_result;
  reg [31:0] result;
  reg [15:0] address;
  reg [31:0] data_out;
  reg [31:0] data_in;
  reg [31:0] carry;
  reg [31:0] s_output_address_stb;
  reg [31:0] s_output_we_stb;
  reg [31:0] s_output_data_in_stb;
  reg [31:0] s_output_address;
  reg [31:0] s_output_we;
  reg [31:0] s_output_data_in;
  reg [31:0] s_input_data_out_ack;
  reg [7:0] state;
  output reg exception;
  reg [28:0] instructions [175:0];
  reg [31:0] memory [4096:0];
  reg [31:0] registers [15:0];
  wire [31:0] operand_a;
  wire [31:0] operand_b;
  wire [31:0] register_a;
  wire [31:0] register_b;
  wire [15:0] literal;
  wire [4:0] opcode;
  wire [3:0] address_a;
  wire [3:0] address_b;
  wire [3:0] address_z;
  wire [15:0] load_address;
  wire [15:0] store_address;
  wire [31:0] store_data;
  wire  store_enable;

  //////////////////////////////////////////////////////////////////////////////
  // INSTRUCTION INITIALIZATION                                                 
  //                                                                            
  // Initialise the contents of the instruction memory                          
  //
  // Intruction Set
  // ==============
  // 0 {'literal': True, 'op': 'literal'}
  // 1 {'literal': True, 'op': 'addl'}
  // 2 {'literal': False, 'op': 'store'}
  // 3 {'literal': True, 'op': 'call'}
  // 4 {'literal': False, 'op': 'stop'}
  // 5 {'literal': False, 'op': 'load'}
  // 6 {'literal': False, 'op': 'write'}
  // 7 {'literal': False, 'op': 'greater'}
  // 8 {'literal': True, 'op': 'jmp_if_false'}
  // 9 {'literal': False, 'op': 'a_lo'}
  // 10 {'literal': False, 'line': 17, 'file': '/home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c', 'op': 'report'}
  // 11 {'literal': False, 'op': 'add'}
  // 12 {'literal': True, 'op': 'goto'}
  // 13 {'literal': False, 'line': 21, 'file': '/home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c', 'op': 'report'}
  // 14 {'literal': False, 'op': 'read'}
  // 15 {'literal': False, 'op': 'equal'}
  // 16 {'literal': False, 'line': 23, 'file': '/home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c', 'op': 'assert'}
  // 17 {'literal': False, 'op': 'return'}
  // Intructions
  // ===========
  
  initial
  begin
    instructions[0] = {5'd0, 4'd3, 4'd0, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 26 {'literal': 0, 'z': 3, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 26, 'op': 'literal'}
    instructions[1] = {5'd0, 4'd4, 4'd0, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 26 {'literal': 0, 'z': 4, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 26, 'op': 'literal'}
    instructions[2] = {5'd1, 4'd3, 4'd3, 16'd4};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 26 {'a': 3, 'literal': 4, 'z': 3, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 26, 'op': 'addl'}
    instructions[3] = {5'd0, 4'd8, 4'd0, 16'd3};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 4 {'literal': 3, 'z': 8, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 4, 'op': 'literal'}
    instructions[4] = {5'd0, 4'd2, 4'd0, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 4 {'literal': 0, 'z': 2, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 4, 'op': 'literal'}
    instructions[5] = {5'd2, 4'd0, 4'd2, 16'd8};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 4 {'a': 2, 'b': 8, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 4, 'op': 'store'}
    instructions[6] = {5'd0, 4'd8, 4'd0, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 1 {'literal': 0, 'z': 8, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 1, 'op': 'literal'}
    instructions[7] = {5'd0, 4'd2, 4'd0, 16'd1};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 1 {'literal': 1, 'z': 2, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 1, 'op': 'literal'}
    instructions[8] = {5'd2, 4'd0, 4'd2, 16'd8};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 1 {'a': 2, 'b': 8, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 1, 'op': 'store'}
    instructions[9] = {5'd0, 4'd8, 4'd0, 16'd1};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 2 {'literal': 1, 'z': 8, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 2, 'op': 'literal'}
    instructions[10] = {5'd0, 4'd2, 4'd0, 16'd2};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 2 {'literal': 2, 'z': 2, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 2, 'op': 'literal'}
    instructions[11] = {5'd2, 4'd0, 4'd2, 16'd8};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 2 {'a': 2, 'b': 8, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 2, 'op': 'store'}
    instructions[12] = {5'd0, 4'd8, 4'd0, 16'd2};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 3 {'literal': 2, 'z': 8, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 3, 'op': 'literal'}
    instructions[13] = {5'd0, 4'd2, 4'd0, 16'd3};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 3 {'literal': 3, 'z': 2, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 3, 'op': 'literal'}
    instructions[14] = {5'd2, 4'd0, 4'd2, 16'd8};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 3 {'a': 2, 'b': 8, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 3, 'op': 'store'}
    instructions[15] = {5'd1, 4'd7, 4'd4, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 26 {'a': 4, 'literal': 0, 'z': 7, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 26, 'op': 'addl'}
    instructions[16] = {5'd1, 4'd4, 4'd3, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 26 {'a': 3, 'literal': 0, 'z': 4, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 26, 'op': 'addl'}
    instructions[17] = {5'd3, 4'd6, 4'd0, 16'd19};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 26 {'z': 6, 'label': 19, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 26, 'op': 'call'}
    instructions[18] = {5'd4, 4'd0, 4'd0, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 26 {'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 26, 'op': 'stop'}
    instructions[19] = {5'd1, 4'd3, 4'd3, 16'd1};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 6 {'a': 3, 'literal': 1, 'z': 3, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 6, 'op': 'addl'}
    instructions[20] = {5'd0, 4'd8, 4'd0, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 9 {'literal': 0, 'z': 8, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 9, 'op': 'literal'}
    instructions[21] = {5'd2, 4'd0, 4'd3, 16'd8};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 9 {'a': 3, 'comment': 'push', 'b': 8, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 9, 'op': 'store'}
    instructions[22] = {5'd1, 4'd3, 4'd3, 16'd1};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 9 {'a': 3, 'literal': 1, 'z': 3, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 9, 'op': 'addl'}
    instructions[23] = {5'd0, 4'd8, 4'd0, 16'd2};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 9 {'literal': 2, 'z': 8, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 9, 'op': 'literal'}
    instructions[24] = {5'd1, 4'd2, 4'd8, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 9 {'a': 8, 'literal': 0, 'z': 2, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 9, 'op': 'addl'}
    instructions[25] = {5'd5, 4'd8, 4'd2, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 9 {'a': 2, 'z': 8, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 9, 'op': 'load'}
    instructions[26] = {5'd1, 4'd3, 4'd3, -16'd1};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 9 {'a': 3, 'comment': 'pop', 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 9, 'literal': -1, 'z': 3, 'op': 'addl'}
    instructions[27] = {5'd5, 4'd0, 4'd3, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 9 {'a': 3, 'z': 0, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 9, 'op': 'load'}
    instructions[28] = {5'd6, 4'd0, 4'd0, 16'd8};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 9 {'a': 0, 'b': 8, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 9, 'op': 'write'}
    instructions[29] = {5'd1, 4'd3, 4'd3, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 9 {'a': 3, 'literal': 0, 'z': 3, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 9, 'op': 'addl'}
    instructions[30] = {5'd0, 4'd8, 4'd0, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 11 {'literal': 0, 'z': 8, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 11, 'op': 'literal'}
    instructions[31] = {5'd1, 4'd2, 4'd4, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 11 {'a': 4, 'literal': 0, 'z': 2, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 11, 'op': 'addl'}
    instructions[32] = {5'd2, 4'd0, 4'd2, 16'd8};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 11 {'a': 2, 'b': 8, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 11, 'op': 'store'}
    instructions[33] = {5'd1, 4'd8, 4'd4, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 11 {'a': 4, 'literal': 0, 'z': 8, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 11, 'op': 'addl'}
    instructions[34] = {5'd1, 4'd2, 4'd8, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 11 {'a': 8, 'literal': 0, 'z': 2, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 11, 'op': 'addl'}
    instructions[35] = {5'd5, 4'd8, 4'd2, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 11 {'a': 2, 'z': 8, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 11, 'op': 'load'}
    instructions[36] = {5'd2, 4'd0, 4'd3, 16'd8};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 11 {'a': 3, 'comment': 'push', 'b': 8, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 11, 'op': 'store'}
    instructions[37] = {5'd1, 4'd3, 4'd3, 16'd1};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 11 {'a': 3, 'literal': 1, 'z': 3, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 11, 'op': 'addl'}
    instructions[38] = {5'd0, 4'd8, 4'd0, 16'd256};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 11 {'literal': 256, 'z': 8, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 11, 'op': 'literal'}
    instructions[39] = {5'd1, 4'd3, 4'd3, -16'd1};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 11 {'a': 3, 'comment': 'pop', 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 11, 'literal': -1, 'z': 3, 'op': 'addl'}
    instructions[40] = {5'd5, 4'd10, 4'd3, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 11 {'a': 3, 'z': 10, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 11, 'op': 'load'}
    instructions[41] = {5'd7, 4'd8, 4'd8, 16'd10};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 11 {'a': 8, 'z': 8, 'b': 10, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 11, 'op': 'greater'}
    instructions[42] = {5'd8, 4'd0, 4'd8, 16'd111};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 11 {'a': 8, 'label': 111, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 11, 'op': 'jmp_if_false'}
    instructions[43] = {5'd0, 4'd8, 4'd0, 16'd1};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 12 {'literal': 1, 'z': 8, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 12, 'op': 'literal'}
    instructions[44] = {5'd1, 4'd2, 4'd8, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 12 {'a': 8, 'literal': 0, 'z': 2, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 12, 'op': 'addl'}
    instructions[45] = {5'd5, 4'd8, 4'd2, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 12 {'a': 2, 'z': 8, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 12, 'op': 'load'}
    instructions[46] = {5'd2, 4'd0, 4'd3, 16'd8};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 12 {'a': 3, 'comment': 'push', 'b': 8, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 12, 'op': 'store'}
    instructions[47] = {5'd1, 4'd3, 4'd3, 16'd1};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 12 {'a': 3, 'literal': 1, 'z': 3, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 12, 'op': 'addl'}
    instructions[48] = {5'd1, 4'd8, 4'd4, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 12 {'a': 4, 'literal': 0, 'z': 8, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 12, 'op': 'addl'}
    instructions[49] = {5'd1, 4'd2, 4'd8, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 12 {'a': 8, 'literal': 0, 'z': 2, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 12, 'op': 'addl'}
    instructions[50] = {5'd5, 4'd8, 4'd2, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 12 {'a': 2, 'z': 8, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 12, 'op': 'load'}
    instructions[51] = {5'd1, 4'd3, 4'd3, -16'd1};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 12 {'a': 3, 'comment': 'pop', 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 12, 'literal': -1, 'z': 3, 'op': 'addl'}
    instructions[52] = {5'd5, 4'd0, 4'd3, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 12 {'a': 3, 'z': 0, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 12, 'op': 'load'}
    instructions[53] = {5'd6, 4'd0, 4'd0, 16'd8};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 12 {'a': 0, 'b': 8, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 12, 'op': 'write'}
    instructions[54] = {5'd1, 4'd3, 4'd3, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 12 {'a': 3, 'literal': 0, 'z': 3, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 12, 'op': 'addl'}
    instructions[55] = {5'd0, 4'd8, 4'd0, 16'd3};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 13 {'literal': 3, 'z': 8, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 13, 'op': 'literal'}
    instructions[56] = {5'd1, 4'd2, 4'd8, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 13 {'a': 8, 'literal': 0, 'z': 2, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 13, 'op': 'addl'}
    instructions[57] = {5'd5, 4'd8, 4'd2, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 13 {'a': 2, 'z': 8, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 13, 'op': 'load'}
    instructions[58] = {5'd2, 4'd0, 4'd3, 16'd8};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 13 {'a': 3, 'comment': 'push', 'b': 8, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 13, 'op': 'store'}
    instructions[59] = {5'd1, 4'd3, 4'd3, 16'd1};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 13 {'a': 3, 'literal': 1, 'z': 3, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 13, 'op': 'addl'}
    instructions[60] = {5'd1, 4'd8, 4'd4, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 13 {'a': 4, 'literal': 0, 'z': 8, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 13, 'op': 'addl'}
    instructions[61] = {5'd1, 4'd2, 4'd8, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 13 {'a': 8, 'literal': 0, 'z': 2, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 13, 'op': 'addl'}
    instructions[62] = {5'd5, 4'd8, 4'd2, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 13 {'a': 2, 'z': 8, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 13, 'op': 'load'}
    instructions[63] = {5'd1, 4'd3, 4'd3, -16'd1};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 13 {'a': 3, 'comment': 'pop', 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 13, 'literal': -1, 'z': 3, 'op': 'addl'}
    instructions[64] = {5'd5, 4'd0, 4'd3, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 13 {'a': 3, 'z': 0, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 13, 'op': 'load'}
    instructions[65] = {5'd6, 4'd0, 4'd0, 16'd8};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 13 {'a': 0, 'b': 8, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 13, 'op': 'write'}
    instructions[66] = {5'd1, 4'd3, 4'd3, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 13 {'a': 3, 'literal': 0, 'z': 3, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 13, 'op': 'addl'}
    instructions[67] = {5'd0, 4'd8, 4'd0, 16'd2};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 14 {'literal': 2, 'z': 8, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 14, 'op': 'literal'}
    instructions[68] = {5'd1, 4'd2, 4'd8, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 14 {'a': 8, 'literal': 0, 'z': 2, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 14, 'op': 'addl'}
    instructions[69] = {5'd5, 4'd8, 4'd2, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 14 {'a': 2, 'z': 8, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 14, 'op': 'load'}
    instructions[70] = {5'd2, 4'd0, 4'd3, 16'd8};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 14 {'a': 3, 'comment': 'push', 'b': 8, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 14, 'op': 'store'}
    instructions[71] = {5'd1, 4'd3, 4'd3, 16'd1};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 14 {'a': 3, 'literal': 1, 'z': 3, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 14, 'op': 'addl'}
    instructions[72] = {5'd0, 4'd8, 4'd0, 16'd1};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 14 {'literal': 1, 'z': 8, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 14, 'op': 'literal'}
    instructions[73] = {5'd1, 4'd3, 4'd3, -16'd1};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 14 {'a': 3, 'comment': 'pop', 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 14, 'literal': -1, 'z': 3, 'op': 'addl'}
    instructions[74] = {5'd5, 4'd0, 4'd3, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 14 {'a': 3, 'z': 0, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 14, 'op': 'load'}
    instructions[75] = {5'd6, 4'd0, 4'd0, 16'd8};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 14 {'a': 0, 'b': 8, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 14, 'op': 'write'}
    instructions[76] = {5'd1, 4'd3, 4'd3, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 14 {'a': 3, 'literal': 0, 'z': 3, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 14, 'op': 'addl'}
    instructions[77] = {5'd0, 4'd8, 4'd0, 16'd2};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 15 {'literal': 2, 'z': 8, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 15, 'op': 'literal'}
    instructions[78] = {5'd1, 4'd2, 4'd8, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 15 {'a': 8, 'literal': 0, 'z': 2, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 15, 'op': 'addl'}
    instructions[79] = {5'd5, 4'd8, 4'd2, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 15 {'a': 2, 'z': 8, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 15, 'op': 'load'}
    instructions[80] = {5'd2, 4'd0, 4'd3, 16'd8};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 15 {'a': 3, 'comment': 'push', 'b': 8, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 15, 'op': 'store'}
    instructions[81] = {5'd1, 4'd3, 4'd3, 16'd1};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 15 {'a': 3, 'literal': 1, 'z': 3, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 15, 'op': 'addl'}
    instructions[82] = {5'd0, 4'd8, 4'd0, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 15 {'literal': 0, 'z': 8, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 15, 'op': 'literal'}
    instructions[83] = {5'd1, 4'd3, 4'd3, -16'd1};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 15 {'a': 3, 'comment': 'pop', 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 15, 'literal': -1, 'z': 3, 'op': 'addl'}
    instructions[84] = {5'd5, 4'd0, 4'd3, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 15 {'a': 3, 'z': 0, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 15, 'op': 'load'}
    instructions[85] = {5'd6, 4'd0, 4'd0, 16'd8};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 15 {'a': 0, 'b': 8, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 15, 'op': 'write'}
    instructions[86] = {5'd1, 4'd3, 4'd3, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 15 {'a': 3, 'literal': 0, 'z': 3, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 15, 'op': 'addl'}
    instructions[87] = {5'd1, 4'd8, 4'd4, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 16 {'a': 4, 'literal': 0, 'z': 8, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 16, 'op': 'addl'}
    instructions[88] = {5'd1, 4'd2, 4'd8, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 16 {'a': 8, 'literal': 0, 'z': 2, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 16, 'op': 'addl'}
    instructions[89] = {5'd5, 4'd8, 4'd2, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 16 {'a': 2, 'z': 8, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 16, 'op': 'load'}
    instructions[90] = {5'd9, 4'd8, 4'd8, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 16 {'a': 8, 'z': 8, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 16, 'op': 'a_lo'}
    instructions[91] = {5'd10, 4'd0, 4'd0, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 16 {'line': 17, 'file': '/home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c', 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 16, 'op': 'report'}
    instructions[92] = {5'd1, 4'd8, 4'd4, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 11 {'a': 4, 'literal': 0, 'z': 8, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 11, 'op': 'addl'}
    instructions[93] = {5'd1, 4'd2, 4'd8, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 11 {'a': 8, 'literal': 0, 'z': 2, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 11, 'op': 'addl'}
    instructions[94] = {5'd5, 4'd8, 4'd2, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 11 {'a': 2, 'z': 8, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 11, 'op': 'load'}
    instructions[95] = {5'd2, 4'd0, 4'd3, 16'd8};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 11 {'a': 3, 'comment': 'push', 'b': 8, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 11, 'op': 'store'}
    instructions[96] = {5'd1, 4'd3, 4'd3, 16'd1};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 11 {'a': 3, 'literal': 1, 'z': 3, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 11, 'op': 'addl'}
    instructions[97] = {5'd0, 4'd8, 4'd0, 16'd1};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 11 {'literal': 1, 'z': 8, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 11, 'op': 'literal'}
    instructions[98] = {5'd2, 4'd0, 4'd3, 16'd8};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 11 {'a': 3, 'comment': 'push', 'b': 8, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 11, 'op': 'store'}
    instructions[99] = {5'd1, 4'd3, 4'd3, 16'd1};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 11 {'a': 3, 'literal': 1, 'z': 3, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 11, 'op': 'addl'}
    instructions[100] = {5'd1, 4'd8, 4'd4, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 11 {'a': 4, 'literal': 0, 'z': 8, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 11, 'op': 'addl'}
    instructions[101] = {5'd1, 4'd2, 4'd8, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 11 {'a': 8, 'literal': 0, 'z': 2, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 11, 'op': 'addl'}
    instructions[102] = {5'd5, 4'd8, 4'd2, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 11 {'a': 2, 'z': 8, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 11, 'op': 'load'}
    instructions[103] = {5'd1, 4'd3, 4'd3, -16'd1};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 11 {'a': 3, 'comment': 'pop', 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 11, 'literal': -1, 'z': 3, 'op': 'addl'}
    instructions[104] = {5'd5, 4'd10, 4'd3, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 11 {'a': 3, 'z': 10, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 11, 'op': 'load'}
    instructions[105] = {5'd11, 4'd8, 4'd8, 16'd10};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 11 {'a': 8, 'z': 8, 'b': 10, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 11, 'op': 'add'}
    instructions[106] = {5'd1, 4'd2, 4'd4, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 11 {'a': 4, 'literal': 0, 'z': 2, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 11, 'op': 'addl'}
    instructions[107] = {5'd2, 4'd0, 4'd2, 16'd8};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 11 {'a': 2, 'b': 8, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 11, 'op': 'store'}
    instructions[108] = {5'd1, 4'd3, 4'd3, -16'd1};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 11 {'a': 3, 'comment': 'pop', 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 11, 'literal': -1, 'z': 3, 'op': 'addl'}
    instructions[109] = {5'd5, 4'd8, 4'd3, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 11 {'a': 3, 'z': 8, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 11, 'op': 'load'}
    instructions[110] = {5'd12, 4'd0, 4'd0, 16'd33};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 11 {'label': 33, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 11, 'op': 'goto'}
    instructions[111] = {5'd0, 4'd8, 4'd0, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 19 {'literal': 0, 'z': 8, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 19, 'op': 'literal'}
    instructions[112] = {5'd1, 4'd2, 4'd4, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 19 {'a': 4, 'literal': 0, 'z': 2, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 19, 'op': 'addl'}
    instructions[113] = {5'd2, 4'd0, 4'd2, 16'd8};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 19 {'a': 2, 'b': 8, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 19, 'op': 'store'}
    instructions[114] = {5'd1, 4'd8, 4'd4, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 19 {'a': 4, 'literal': 0, 'z': 8, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 19, 'op': 'addl'}
    instructions[115] = {5'd1, 4'd2, 4'd8, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 19 {'a': 8, 'literal': 0, 'z': 2, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 19, 'op': 'addl'}
    instructions[116] = {5'd5, 4'd8, 4'd2, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 19 {'a': 2, 'z': 8, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 19, 'op': 'load'}
    instructions[117] = {5'd2, 4'd0, 4'd3, 16'd8};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 19 {'a': 3, 'comment': 'push', 'b': 8, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 19, 'op': 'store'}
    instructions[118] = {5'd1, 4'd3, 4'd3, 16'd1};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 19 {'a': 3, 'literal': 1, 'z': 3, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 19, 'op': 'addl'}
    instructions[119] = {5'd0, 4'd8, 4'd0, 16'd256};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 19 {'literal': 256, 'z': 8, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 19, 'op': 'literal'}
    instructions[120] = {5'd1, 4'd3, 4'd3, -16'd1};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 19 {'a': 3, 'comment': 'pop', 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 19, 'literal': -1, 'z': 3, 'op': 'addl'}
    instructions[121] = {5'd5, 4'd10, 4'd3, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 19 {'a': 3, 'z': 10, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 19, 'op': 'load'}
    instructions[122] = {5'd7, 4'd8, 4'd8, 16'd10};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 19 {'a': 8, 'z': 8, 'b': 10, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 19, 'op': 'greater'}
    instructions[123] = {5'd8, 4'd0, 4'd8, 16'd173};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 19 {'a': 8, 'label': 173, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 19, 'op': 'jmp_if_false'}
    instructions[124] = {5'd1, 4'd8, 4'd4, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 20 {'a': 4, 'literal': 0, 'z': 8, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 20, 'op': 'addl'}
    instructions[125] = {5'd1, 4'd2, 4'd8, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 20 {'a': 8, 'literal': 0, 'z': 2, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 20, 'op': 'addl'}
    instructions[126] = {5'd5, 4'd8, 4'd2, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 20 {'a': 2, 'z': 8, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 20, 'op': 'load'}
    instructions[127] = {5'd9, 4'd8, 4'd8, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 20 {'a': 8, 'z': 8, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 20, 'op': 'a_lo'}
    instructions[128] = {5'd13, 4'd0, 4'd0, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 20 {'line': 21, 'file': '/home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c', 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 20, 'op': 'report'}
    instructions[129] = {5'd0, 4'd8, 4'd0, 16'd1};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 21 {'literal': 1, 'z': 8, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 21, 'op': 'literal'}
    instructions[130] = {5'd1, 4'd2, 4'd8, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 21 {'a': 8, 'literal': 0, 'z': 2, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 21, 'op': 'addl'}
    instructions[131] = {5'd5, 4'd8, 4'd2, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 21 {'a': 2, 'z': 8, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 21, 'op': 'load'}
    instructions[132] = {5'd2, 4'd0, 4'd3, 16'd8};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 21 {'a': 3, 'comment': 'push', 'b': 8, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 21, 'op': 'store'}
    instructions[133] = {5'd1, 4'd3, 4'd3, 16'd1};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 21 {'a': 3, 'literal': 1, 'z': 3, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 21, 'op': 'addl'}
    instructions[134] = {5'd1, 4'd8, 4'd4, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 21 {'a': 4, 'literal': 0, 'z': 8, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 21, 'op': 'addl'}
    instructions[135] = {5'd1, 4'd2, 4'd8, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 21 {'a': 8, 'literal': 0, 'z': 2, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 21, 'op': 'addl'}
    instructions[136] = {5'd5, 4'd8, 4'd2, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 21 {'a': 2, 'z': 8, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 21, 'op': 'load'}
    instructions[137] = {5'd1, 4'd3, 4'd3, -16'd1};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 21 {'a': 3, 'comment': 'pop', 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 21, 'literal': -1, 'z': 3, 'op': 'addl'}
    instructions[138] = {5'd5, 4'd0, 4'd3, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 21 {'a': 3, 'z': 0, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 21, 'op': 'load'}
    instructions[139] = {5'd6, 4'd0, 4'd0, 16'd8};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 21 {'a': 0, 'b': 8, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 21, 'op': 'write'}
    instructions[140] = {5'd1, 4'd3, 4'd3, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 21 {'a': 3, 'literal': 0, 'z': 3, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 21, 'op': 'addl'}
    instructions[141] = {5'd1, 4'd8, 4'd4, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 22 {'a': 4, 'literal': 0, 'z': 8, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 22, 'op': 'addl'}
    instructions[142] = {5'd1, 4'd2, 4'd8, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 22 {'a': 8, 'literal': 0, 'z': 2, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 22, 'op': 'addl'}
    instructions[143] = {5'd5, 4'd8, 4'd2, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 22 {'a': 2, 'z': 8, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 22, 'op': 'load'}
    instructions[144] = {5'd2, 4'd0, 4'd3, 16'd8};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 22 {'a': 3, 'comment': 'push', 'b': 8, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 22, 'op': 'store'}
    instructions[145] = {5'd1, 4'd3, 4'd3, 16'd1};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 22 {'a': 3, 'literal': 1, 'z': 3, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 22, 'op': 'addl'}
    instructions[146] = {5'd0, 4'd8, 4'd0, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 22 {'literal': 0, 'z': 8, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 22, 'op': 'literal'}
    instructions[147] = {5'd1, 4'd2, 4'd8, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 22 {'a': 8, 'literal': 0, 'z': 2, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 22, 'op': 'addl'}
    instructions[148] = {5'd5, 4'd8, 4'd2, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 22 {'a': 2, 'z': 8, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 22, 'op': 'load'}
    instructions[149] = {5'd14, 4'd8, 4'd8, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 22 {'a': 8, 'z': 8, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 22, 'op': 'read'}
    instructions[150] = {5'd1, 4'd3, 4'd3, -16'd1};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 22 {'a': 3, 'comment': 'pop', 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 22, 'literal': -1, 'z': 3, 'op': 'addl'}
    instructions[151] = {5'd5, 4'd10, 4'd3, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 22 {'a': 3, 'z': 10, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 22, 'op': 'load'}
    instructions[152] = {5'd15, 4'd8, 4'd8, 16'd10};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 22 {'a': 8, 'z': 8, 'b': 10, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 22, 'op': 'equal'}
    instructions[153] = {5'd16, 4'd0, 4'd8, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 22 {'a': 8, 'line': 23, 'file': '/home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c', 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 22, 'op': 'assert'}
    instructions[154] = {5'd1, 4'd8, 4'd4, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 19 {'a': 4, 'literal': 0, 'z': 8, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 19, 'op': 'addl'}
    instructions[155] = {5'd1, 4'd2, 4'd8, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 19 {'a': 8, 'literal': 0, 'z': 2, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 19, 'op': 'addl'}
    instructions[156] = {5'd5, 4'd8, 4'd2, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 19 {'a': 2, 'z': 8, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 19, 'op': 'load'}
    instructions[157] = {5'd2, 4'd0, 4'd3, 16'd8};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 19 {'a': 3, 'comment': 'push', 'b': 8, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 19, 'op': 'store'}
    instructions[158] = {5'd1, 4'd3, 4'd3, 16'd1};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 19 {'a': 3, 'literal': 1, 'z': 3, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 19, 'op': 'addl'}
    instructions[159] = {5'd0, 4'd8, 4'd0, 16'd1};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 19 {'literal': 1, 'z': 8, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 19, 'op': 'literal'}
    instructions[160] = {5'd2, 4'd0, 4'd3, 16'd8};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 19 {'a': 3, 'comment': 'push', 'b': 8, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 19, 'op': 'store'}
    instructions[161] = {5'd1, 4'd3, 4'd3, 16'd1};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 19 {'a': 3, 'literal': 1, 'z': 3, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 19, 'op': 'addl'}
    instructions[162] = {5'd1, 4'd8, 4'd4, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 19 {'a': 4, 'literal': 0, 'z': 8, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 19, 'op': 'addl'}
    instructions[163] = {5'd1, 4'd2, 4'd8, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 19 {'a': 8, 'literal': 0, 'z': 2, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 19, 'op': 'addl'}
    instructions[164] = {5'd5, 4'd8, 4'd2, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 19 {'a': 2, 'z': 8, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 19, 'op': 'load'}
    instructions[165] = {5'd1, 4'd3, 4'd3, -16'd1};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 19 {'a': 3, 'comment': 'pop', 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 19, 'literal': -1, 'z': 3, 'op': 'addl'}
    instructions[166] = {5'd5, 4'd10, 4'd3, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 19 {'a': 3, 'z': 10, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 19, 'op': 'load'}
    instructions[167] = {5'd11, 4'd8, 4'd8, 16'd10};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 19 {'a': 8, 'z': 8, 'b': 10, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 19, 'op': 'add'}
    instructions[168] = {5'd1, 4'd2, 4'd4, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 19 {'a': 4, 'literal': 0, 'z': 2, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 19, 'op': 'addl'}
    instructions[169] = {5'd2, 4'd0, 4'd2, 16'd8};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 19 {'a': 2, 'b': 8, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 19, 'op': 'store'}
    instructions[170] = {5'd1, 4'd3, 4'd3, -16'd1};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 19 {'a': 3, 'comment': 'pop', 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 19, 'literal': -1, 'z': 3, 'op': 'addl'}
    instructions[171] = {5'd5, 4'd8, 4'd3, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 19 {'a': 3, 'z': 8, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 19, 'op': 'load'}
    instructions[172] = {5'd12, 4'd0, 4'd0, 16'd114};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 19 {'label': 114, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 19, 'op': 'goto'}
    instructions[173] = {5'd1, 4'd3, 4'd4, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 6 {'a': 4, 'literal': 0, 'z': 3, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 6, 'op': 'addl'}
    instructions[174] = {5'd1, 4'd4, 4'd7, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 6 {'a': 7, 'literal': 0, 'z': 4, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 6, 'op': 'addl'}
    instructions[175] = {5'd17, 4'd0, 4'd6, 16'd0};///home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 6 {'a': 6, 'trace': /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c : 6, 'op': 'return'}
  end

  
  always @(posedge clk)
  begin
    load_data <= memory[load_address];
    if(store_enable && state == execute) begin
      memory[store_address] <= store_data;
    end
  end


  //////////////////////////////////////////////////////////////////////////////
  // PIPELINE STAGE 1 -- FETCH INSTRUCTION
  //                                                                            
  
  always @(posedge clk)
  begin
    //implement memory for instructions
    if (state == instruction_fetch || state == operand_fetch || state == execute) begin
      instruction <= instructions[program_counter];
      program_counter_1 <= program_counter;
    end
  end

  assign opcode    = instruction[28:24];
  assign address_z = instruction[23:20];
  assign address_a = instruction[19:16];
  assign address_b = instruction[3:0];
  assign literal   = instruction[15:0];

  //////////////////////////////////////////////////////////////////////////////
  // PIPELINE STAGE 2 -- FETCH OPERANDS
  //                                                                            
  
  always @(posedge clk)
  begin
    if (write_enable) begin
      registers[address_z_3] <= result;
    end
    if (state == operand_fetch || state == execute) begin
      opcode_2 <= opcode;
      literal_2 <= literal;
      address_a_2 <= address_a;
      address_b_2 <= address_b;
      address_z_2 <= address_z;
      program_counter_2 <= program_counter_1;
    end
  end
  assign register_a = registers[address_a_2];
  assign register_b = registers[address_b_2];
  assign operand_a = (address_a_2 == address_z_3 && write_enable)?result:register_a;
  assign operand_b = (address_b_2 == address_z_3 && write_enable)?result:register_b;
  assign store_address = operand_a;
  assign load_address = operand_a;
  assign store_data = operand_b;
  assign store_enable = (opcode_2==2);

  //////////////////////////////////////////////////////////////////////////////
  // PIPELINE STAGE 3 -- EXECUTE
  //                                                                            
  
  always @(posedge clk)
  begin

  write_enable <= 0;
  timer_clock <= timer_clock + 1;
  case(state)

    //instruction_fetch
    instruction_fetch: begin
      program_counter <= program_counter + 1;
      state <= operand_fetch;
    end
    //operand_fetch
    operand_fetch: begin
      program_counter <= program_counter + 1;
      state <= execute;
    end
    //execute
    execute: begin
      program_counter <= program_counter + 1;
      address_z_3 <= address_z_2;
      case(opcode_2)

        //literal
        16'd0:
        begin
          result<=$signed(literal_2);
          write_enable <= 1;
        end

        //addl
        16'd1:
        begin
          result<=operand_a + literal_2;
          write_enable <= 1;
        end

        //store
        16'd2:
        begin
        end

        //call
        16'd3:
        begin
          result <= program_counter_2 + 1;
          write_enable <= 1;
          program_counter <= literal_2;
          state <= instruction_fetch;
        end

        //stop
        16'd4:
        begin
        state <= stop;
        end

        //load
        16'd5:
        begin
          state <= load;
        end

        //write
        16'd6:
        begin
          state <= write;
          write_output <= operand_a;
          write_value <= operand_b;
        end

        //greater
        16'd7:
        begin
          result <= $signed(operand_a) > $signed(operand_b);
          write_enable <= 1;
        end

        //jmp_if_false
        16'd8:
        begin
          if (operand_a == 0) begin
            program_counter <= literal_2;
            state <= instruction_fetch;
          end
        end

        //a_lo
        16'd9:
        begin
          a_lo <= operand_a;
          result <= a_lo;
          write_enable <= 1;
        end

        //report
        16'd10:
        begin
          $display ("%d (report (int) at line: 17 in file: /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c)", $signed(a_lo));
        end

        //add
        16'd11:
        begin
          long_result = operand_a + operand_b;
          result <= long_result[31:0];
          carry[0] <= long_result[32];
          write_enable <= 1;
        end

        //goto
        16'd12:
        begin
          program_counter <= literal_2;
          state <= instruction_fetch;
        end

        //report
        16'd13:
        begin
          $display ("%d (report (int) at line: 21 in file: /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c)", $signed(a_lo));
        end

        //read
        16'd14:
        begin
          state <= read;
          read_input <= operand_a;
        end

        //equal
        16'd15:
        begin
          result <= operand_a == operand_b;
          write_enable <= 1;
        end

        //assert
        16'd16:
        begin
          if (operand_a == 0) begin
            $display("Assertion failed at line: 23 in file: /home/jon/portable_ip_library/components/memory/ram/test/single_port_ram_tb.c");
            $finish_and_return(1);
          end
        end

        //return
        16'd17:
        begin
          program_counter <= operand_a;
          state <= instruction_fetch;
        end

      endcase

    end

    read:
    begin
      case(read_input)
      3:
      begin
        s_input_data_out_ack <= 1;
        if (s_input_data_out_ack && input_data_out_stb) begin
          result <= input_data_out;
          write_enable <= 1;
          s_input_data_out_ack <= 0;
          state <= execute;
        end
      end
      endcase
    end

    write:
    begin
      case(write_output)
      0:
      begin
        s_output_address_stb <= 1;
        s_output_address <= write_value;
        if (output_address_ack && s_output_address_stb) begin
          s_output_address_stb <= 0;
          state <= execute;
        end
      end
      1:
      begin
        s_output_we_stb <= 1;
        s_output_we <= write_value;
        if (output_we_ack && s_output_we_stb) begin
          s_output_we_stb <= 0;
          state <= execute;
        end
      end
      2:
      begin
        s_output_data_in_stb <= 1;
        s_output_data_in <= write_value;
        if (output_data_in_ack && s_output_data_in_stb) begin
          s_output_data_in_stb <= 0;
          state <= execute;
        end
      end
      endcase
    end

    load:
    begin
        result <= load_data;
        write_enable <= 1;
        state <= execute;
    end

    wait_state:
    begin
      if (timer) begin
        timer <= timer - 1;
      end else begin
        state <= execute;
      end
    end

    stop:
    begin
    end

    endcase

    if (rst == 1'b1) begin
      timer <= 0;
      timer_clock <= 0;
      program_counter <= 0;
      address_z_3 <= 0;
      result <= 0;
      a = 0;
      b = 0;
      z = 0;
      state <= instruction_fetch;
      s_input_data_out_ack <= 0;
      s_output_address_stb <= 0;
      s_output_we_stb <= 0;
      s_output_data_in_stb <= 0;
    end
  end
  assign input_data_out_ack = s_input_data_out_ack;
  assign output_address_stb = s_output_address_stb;
  assign output_address = s_output_address;
  assign output_we_stb = s_output_we_stb;
  assign output_we = s_output_we;
  assign output_data_in_stb = s_output_data_in_stb;
  assign output_data_in = s_output_data_in;

endmodule
